In [1]:
# from OU text book contingency tables - this one of blood types by population group in Iraq

import numpy as np
from scipy.stats import chi2_contingency


In [3]:
table = np.array([
    [531, 450, 293, 226],
    [174, 150, 133, 36],
    [139, 134, 74, 33]
])

In [4]:
# Perform chi-square test
chi2, p, dof, expected = chi2_contingency(table)

print("Chi-square statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-square statistic: 36.30949210509334
p-value: 2.3999314270995936e-06
Degrees of freedom: 6
Expected frequencies:
 [[533.50189633 463.96965866 316.05562579 186.47281922]
 [175.34428993 152.49136115 103.87694901  61.28739992]
 [135.15381374 117.53898019  80.0674252   47.23978087]]
